### ISSUE TITLE
报错了，编译不通过

### ISSUE THREAD

**Issue by baiguoname** [mineralres/rust-share#1]
我运行cargo build有下面的错误：
PS D:\Rust\rust-share-main> cargo build
   Compiling ctp-futures v0.1.0 (D:\Rust\rust-share-main\crates\ctp-futures)
error: failed to run custom build command for `ctp-futures v0.1.0 (D:\Rust\rust-share-main\crates\ctp-futures)`

Caused by:
  process didn't exit successfully: `D:\Rust\rust-share-main\target\debug\build\ctp-futures-f60b73c04b31ebac\build-script-build` (exit code: 101)
  --- stdout
  tp=Type { kind: Elaborated, display_name: "THOST_TE_RESUME_TYPE" }

  --- stderr
  thread 'main' panicked at '', crates\ctp-futures\build.rs:113:37
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
我的Rust 版本是1.69.0

**Comment by mineralres** [comment]
```
PS C:\Users\xb> cd d:
PS D:\> cd .\develop\github.com\mineralres\rust-share\
PS D:\develop\github.com\mineralres\rust-share> cargo build
   Compiling ctp-futures v0.1.0 (D:\develop\github.com\mineralres\rust-share\crates\ctp-futures)
    Finished dev [unoptimized + debuginfo] target(s) in 4.49s
PS D:\develop\github.com\mineralres\rust-share>
```
我在windows下试了一下是正常的呢

**Comment by baiguoname** [comment]
能看下你的rustc和llvm的版本吗？

**Comment by mineralres** [comment]
rust 1.69
clang version 15.0.7
看你的编译器提示好像是在clang在转换cpp header的时候出现了一些意料之外的情况

**Comment by baiguoname** [comment]
我刚刚把clang换成15.0.7版本，现在编译和测试都能通过

**Comment by baiguoname** [comment]
请问下，我在examples里的ctp_query里面看了各类的查询操作，但是没有看见下单的操作，请问目前该库支持下单吗？

**Comment by mineralres** [comment]
可以下单，对应的api.req_order_insert，函数接口与cpp的都一致，你可以按对应的名字去找相应的接口
