### ISSUE TITLE
订阅完行情，行情回调没有发生。

### ISSUE THREAD

**Issue by baiguoname** [mineralres/rust-share#3]
我在ctp_query有下面的代码
![image](https://github.com/mineralres/rust-share/assets/52092777/b0623320-e001-4ae8-b153-1dac60247804)
上面的代码中，我在第226行订阅了一个行情，并且在第238行打印已接受到的数据的总体长度。但是结果是，这个数据的长度一直为1，没有变化，我猜测是行情回调可能没有成功。

**Comment by baiguoname** [comment]
第236行的打印的`result`是0， 表示行情订阅成功

**Comment by mineralres** [comment]
ctp_query里面使用的是trade_api, 订阅实时行情需要用md_api, 我稍后写一个订阅行情的例子上去

**Comment by mineralres** [comment]
订阅行情的例子已经上传了
