### ISSUE TITLE
编译时error

### ISSUE THREAD

**Issue by dhcn** [mineralres/rust-share#4]
error: failed to run custom build command for `ctp-futures v0.1.0 (/Users/dhcn/Downloads/rust-share-main/crates/ctp-futures)`

Caused by:
  process didn't exit successfully: `/Users/dhcn/Downloads/rust-share-main/target/debug/build/ctp-futures-80259c5b71578461/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-search=./crates/ctp-futures/v_current
  cargo:rustc-link-search=native=/Users/dhcn/Downloads/rust-share-main/crates/ctp-futures/v_current

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/ctp-futures/build.rs:544:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by dhcn** [comment]
问题在于上下文so的文件名有问题，缺lib了

**Comment by mineralres** [comment]
#5
