### ISSUE TITLE
编译时错误

### ISSUE THREAD

**Issue by dhcn** [mineralres/rust-share#5]
$ cargo run --example ctp_query

error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin:/Users/dhcn/.cargo/bin:/Users/dhcn/.cargo/bin:/usr/local/opt/openjdk/bin:/Users/dhcn/.pyenv/shims:/Users/dhcn/.pyenv/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/dhcn/.cargo/bin" VSLANG="1033" ZERO_AR_DATE="1" "cc" "-arch" "x86_64" "-m64" "/var/folders/gp/4jsd92sj4ln0f09sl7l78b740000gn/T/rustc4UoBF7/symbols.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.1300ouxq1by61kba.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.13glgkjn60ou70r5.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.14dv2d9xtycxggav.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.15ffhqq7x797akvq.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.181mdtp0qlqbyhs0.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.18gshbb8mvxibdgj.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.1cfzig8cz82focr.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.1dupeijawpzo8l9.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.1kxta3j2swbx5rju.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.1ocp57etkr7edsm6.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.1qnkl9l9uv2rvi9t.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.1sc3lhjjw562p180.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.1semfxv5zzavgdqd.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.1snvoucv8nvn4av5.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.1t3ijnbpmnkoc3t0.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.1uhbjn3dxa52rj1s.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.1vx8iy196sm2onhg.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.2cmvyytexbkbpi9j.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.2fijndux9s15ldwe.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.2gcx9s7h1t5q3l79.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.2pgl8xni5eatiq62.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.2pz2tnlikzuaq94s.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.2q9aj6uk4r8fggqk.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.2r6p1zzslpv6izd0.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.2s3tvw9kfq5ld7d5.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.2snfgix2vom3hznd.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.2u6lehj3le53st2b.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.2vfaf6chtebvpp1c.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.2xiqnfig9fteeebn.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.2y6uh5jptflc3vph.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.2ybbs35uykgp5xzj.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.30s2pv6dgni407va.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.33mg428x4wmcs7kh.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.363kpat3s8tkmwip.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.3663itselz8ex73p.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.3759jo81y60qi3h3.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.39md14wqaw6o280c.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.3k46t1dr8d70vvt0.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.3mp40rg7wq1otxjg.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.3ofucm2pmnu6zqtb.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.3qgcayj5ct38ezaq.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.3qru1jlj70lt610g.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.3rikb102sn20zsim.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.3ss8z4wemlytfvxc.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.3ttv6tm99hgfpij2.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.3viz1nmtu1cfz2v6.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.3xrthelenuhauor8.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.3yneixizwg8utau4.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.40ohqzg3a7ira8x2.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4am439y90oz3gq86.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4dl239jaswq97ame.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4gnbhlba2g9gfp9r.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4hamiif1ioby51se.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4hfghp310k8zghvo.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4hku6bz678qicnbd.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4iu1z2b2jz1wkiyg.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4jm6j8e233jexiey.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4p26o74vy1uffuxd.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4po3nvt6t2qk0qub.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4pt6mvf3ln62vvoj.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4qg0rabks0bk55hi.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4qvzfbq659pa3rlh.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4swfry4jt8ux7zlz.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4uwi85ahend7gzsz.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4weh3or0lzmwt04g.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4yieox4xm04c6wlf.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4yscuj591upeaxc4.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.4z3sqejdzp92ct43.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.571jpyulnzxwnxrh.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.5cviroogt1feywr4.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.5e42jkooih9s9unz.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.6f8uw0h0kqoxw1q.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.7cmtwr0buas392u.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.9p9p8wx5wb8dy7i.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.bqlujrscejl9k0a.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.ew5asf030k0d0x7.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.g4e4v9b7hq6imt0.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.k840k5xo5tdt058.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.kl0qpjcyz2t7xdu.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.mip3qnhywwipim8.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.o8z570oxldtmcsc.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.p8htdvhye7pgwfw.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.piugit0j3zm4gqn.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.sudqr2buajuvgzw.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.tx94ocoergk68y7.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.vzcf1iwpss8gszs.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.y5fckuy18j3d3v8.rcgu.o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b.bpes0nk4j6ogkq1.rcgu.o" "-L" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps" "-L" "./crates/ctp-futures/v_current" "-L" "/Users/dhcn/Downloads/rust-share-main/crates/ctp-futures/v_current" "-L" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libtracing_subscriber-4f85eefabcb6fdfb.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libchrono-474438fdfc063ff5.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libnum_traits-e751269d9f1b53c7.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libiana_time_zone-5b677efd9bd9f62f.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libcore_foundation_sys-d08a3018e9bc9562.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libtime-b676f4ed23bbe868.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libthread_local-801d700a1e9066bc.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libsharded_slab-4582d764d709032e.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libtracing_serde-0cf2dc607d163ef6.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libserde_json-43a4bd58219fd475.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libryu-e6823da67c358aa5.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libitoa-4c54e873f76406aa.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libserde-8a643d89d806c949.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libtracing_log-b7cafffe4f628bed.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libansi_term-7696091476431a84.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libtracing-4d18ac6ecf412d58.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libmatchers-9bd87b57234b0bd6.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libregex_automata-3f69dd5deb8df126.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libregex_syntax-1049ad906e45afc2.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libregex-7933af9e870db2c7.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libregex_automata-63e198e0cecc1ef5.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libaho_corasick-bf2da850e12f9b9e.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libregex_syntax-da3e4828027b8954.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/liblazy_static-761ffe451ad7ec77.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libtracing_core-7577327c5ec1ae8e.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libonce_cell-77e62f807a8110d1.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libtokio-21995e6229285f23.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libsignal_hook_registry-af0edc3014b67401.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libnum_cpus-06ba324ab28a9e77.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libsocket2-87c9381fc6c8e04b.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libbytes-f44b6b5fc7cfa372.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libmio-e7a97f321feacddf.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libparking_lot-613d5b6b333a8a29.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libparking_lot_core-32484cd1563b2d28.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/liblibc-3beefa042e20582c.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libcfg_if-6800783d25b0712a.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libsmallvec-de2f2fa8c34d54cc.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/liblock_api-49ee6ef103289912.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libscopeguard-630da820626bc167.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/librust_share_util-7c045db343957c04.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libsimple_error-158f6c96c94bc72c.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libencoding-bc4a46ed7c6cc5b4.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libencoding_index_tradchinese-fe811da0ade660c6.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libencoding_index_simpchinese-ef8341390e19c248.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libencoding_index_japanese-50ed255390a43c3a.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libencoding_index_korean-f6cfe29bd9994c11.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libencoding_index_singlebyte-68032799824ea889.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/liblog-82887be0523d535b.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libctp_futures-c8222546d17274c1.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libfutures-67ccf7c3fd8152ef.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libfutures_executor-af5d119288eb5dc8.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libfutures_util-c617d544c369cd8f.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libmemchr-152e05ecbbcd729a.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libfutures_io-6db919b57c13c8d8.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libslab-9cc5864e1ad3272a.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libfutures_channel-03b4035b03f02e72.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libpin_project_lite-855da81f5429afa7.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libfutures_sink-3e56e1f15457c319.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libfutures_task-689b6e2798f3f26b.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libpin_utils-59f62735ca3c436b.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libfutures_core-260f8afc2337b837.rlib" "/Users/dhcn/Downloads/rust-share-main/target/debug/deps/libbincode-6ee644da667eff45.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-6472438448c6c4bd.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-3600ed8016f8face.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libobject-ea51991ef4a3658d.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libmemchr-96b3ff65689c3fce.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-07fa1dec1d2bd3bb.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libgimli-175fd87b93400a41.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-3b326864ccc9e9e8.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd_detect-39dcdc3dac7bf511.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-84429b66c29d7ef9.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-26b6ba85d2896aa6.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libminiz_oxide-3efa691a08d42571.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libadler-81d639bf7b0fb091.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-f27a894b1cbe21a7.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-1b1ed482c4b1447a.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-4e263b0a0b4d1d51.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-6938fc20e09e5c3a.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-f588925d2f9025bc.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-4b6dec082eeb7c38.rlib" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-950dfa4358313a7f.rlib" "-framework" "CoreFoundation" "-liconv" "-lthosttraderapi_se" "-lthostmduserapi_se" "-lSystem" "-lc" "-lm" "-L" "/Users/dhcn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "-o" "/Users/dhcn/Downloads/rust-share-main/target/debug/examples/ctp_query-c0743fcb742ee68b" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: ld: warning: ignoring file ./crates/ctp-futures/v_current/libthostmduserapi_se.so, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
          ld: warning: ignoring file ./crates/ctp-futures/v_current/libthosttraderapi_se.so, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
          Undefined symbols for architecture x86_64:
            "CThostFtdcTraderApi::CreateFtdcTraderApi(char const*)", referenced from:
                ctp_futures::trader_api::create_api::hcb66a124a3a29395 in libctp_futures-c8222546d17274c1.rlib(ctp_futures-c8222546d17274c1.3jht51zv1tu35hn1.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

warning: `ctp_query` (example "ctp_query") generated 2 warnings
error: could not compile `ctp_query` (example "ctp_query") due to previous error; 2 warnings emitted

**Comment by mineralres** [comment]
@dhcn  在什么系统上编译的？

**Comment by dhcn** [comment]
> @dhcn 在什么系统上编译的？

WSL和Mac上都跑不通。
WSL=Windows Subsystem for Linux

**Comment by dhcn** [comment]
> @dhcn 在什么系统上编译的？

从rust的编译面板上可以看到几个从C++生成过来的函数都找不到

**Comment by mineralres** [comment]
我只在win和ubuntu上测试过， 你这两个暂时都没环境测试 😂

**Comment by dhcn** [comment]
> 我只在win和ubuntu上测试过， 你这两个暂时都没环境测试 😂

好，我在这两种环境下测试一下。
