### ISSUE TITLE
如何使用例如OPENCTP这样的第三方平台？

### ISSUE THREAD

**Issue by youyuanrsq** [mineralres/rust-share#6]
如题，是否只需要替换v_current/thosttraderapi_se.dll文件为第三方提供的dll文件，以及对应的账户信息就可以？
`
// 替换成第三方账户信息   
 let account = CtpAccountConfig {
        broker_id: "9999".to_string(),
        account: "143650".to_string(), 
        trade_front: "tcp://180.168.146.187:10201".to_string(),
        md_front: "180.168.146.187:10211".to_string(),
        name_server: "".to_string(),
        auth_code: "0000000000000000".to_string(),
        user_product_info: "".to_string(),
        app_id: "simnow_client_test".to_string(),
        password: "198612".to_string(),
    };`

**Comment by mineralres** [comment]
理论上是这样的，但是第三方的dll跟官方还是有点小区别，可能会crash
